language: node_js
node_js:
  - "12"
install: npm install
script: npm test
env:
  - NODE_ENV=test
deploy:
  provider: npm
  email: wangfupeng1988@163.com
  api_key: 37a2fcde-166c-4ca2-b318-de3fe7a90e0b # 登录 npm ，查看 ~/.npmrc
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
